/**
 * Fallback agent data for when the backend is offline.
 * Sprite keys match CHARACTER_NAMES loaded in BootScene.
 * Positions are on the_ville map (140x100 tiles).
 */
import { AgentState } from './ApiClient';

export const FALLBACK_AGENTS: AgentState[] = [
  {
    id: 'agent_isabella',
    name: 'Isabella Rodriguez',
    location_id: 'cafe',
    current_action: 'Wiping down the counter',
    x: 72, y: 14,
    sprite_key: 'Isabella_Rodriguez',
    description: 'Cafe owner',
    daily_plan: null,
    current_plan_step: 0,
    day_number: 1,
  },
  {
    id: 'agent_klaus',
    name: 'Klaus Mueller',
    location_id: 'library',
    current_action: 'Reading a research paper',
    x: 100, y: 42,
    sprite_key: 'Klaus_Mueller',
    description: 'Research student',
    daily_plan: null,
    current_plan_step: 0,
    day_number: 1,
  },
  {
    id: 'agent_sam',
    name: 'Sam Moore',
    location_id: 'town_square',
    current_action: 'Making morning coffee',
    x: 70, y: 50,
    sprite_key: 'Sam_Moore',
    description: 'A friendly neighbor',
    daily_plan: null,
    current_plan_step: 0,
    day_number: 1,
  },
  {
    id: 'agent_mei',
    name: 'Mei Lin',
    location_id: 'park',
    current_action: 'Sitting on the bench reading',
    x: 74, y: 48,
    sprite_key: 'Mei_Lin',
    description: 'A bookworm',
    daily_plan: null,
    current_plan_step: 0,
    day_number: 1,
  },
  {
    id: 'agent_tom',
    name: 'Tom Moreno',
    location_id: 'house',
    current_action: 'Cooking breakfast',
    x: 60, y: 30,
    sprite_key: 'Tom_Moreno',
    description: 'Retired chef',
    daily_plan: null,
    current_plan_step: 0,
    day_number: 1,
  },
  {
    id: 'agent_latoya',
    name: 'Latoya Williams',
    location_id: 'pharmacy',
    current_action: 'Organizing prescriptions',
    x: 80, y: 36,
    sprite_key: 'Latoya_Williams',
    description: 'Pharmacist',
    daily_plan: null,
    current_plan_step: 0,
    day_number: 1,
  },
];
